### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by BarryYangi** [hanbings/antares#1]
刚刚按照readme弄了一下，但是好像并不能正常使用。

**Comment by hanbings** [comment]
感谢支持！请问能提供报错吗？

在 Cloudflare 的 Workers 页面找到快速编辑
![Cloudflare](https://i.328888.xyz/2023/05/16/ViG0rp.png)

进入快速编辑界面之后在右下角就可以看到开发者控制台
![Cloudflare](https://i.328888.xyz/2023/05/16/ViGOa5.png)

**Comment by BarryYangi** [comment]
![image](https://github.com/hanbings/antares/assets/73282988/d59a30a3-f5e4-4de2-bd8b-27811ad2e53d)
控制台是这样的。

**Comment by BarryYangi** [comment]
![image](https://github.com/hanbings/antares/assets/73282988/0c92c429-edd9-4ae7-9b90-8ca7e295051b)
upload页面能访问但是不能上传。

**Comment by hanbings** [comment]
目前已经修复了该问题，感谢回复！https://github.com/hanbings/antares/commit/e505d653f2c3545022b234d476a2e7aa5879f84a

**Comment by BarryYangi** [comment]
好了，感谢！
